package com.example.lico.database

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "resource_table")
data class ResourceEntity(

    // Defines the table's primary key. Primary keys are unique values that can be autogenerated.
    // They are used to differentiate one entity from another.
    @PrimaryKey(autoGenerate = true)
    var resourceid: Long = 0L,

    // Non-primary key column. Data type is specified in the property.
    @ColumnInfo()
    var resourceName: String = "",

    // Non-primary key column. Data type is specified in the property.
    @ColumnInfo()
    var resourceInfo: String = ""
)
